POST http://localhost:3600/api/auth/signin
Content-Type: application/json

{
    "user":"hugo10",
    "password":"test"
}

### 
POST http://localhost:3600/api/auth/register
Content-Type: application/json

{
    "user":"hugo11",
    "password":"test"
}

###
POST http://localhost:3600/api/auth/token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IjlmODZkMDgxODg0YzdkNjU5YTJmZWFhMGM1NWFkMDE1YTNiZjRmMWIyYjBiODIyY2QxNWQ2YzE1YjBmMDBhMDgiLCJpYXQiOjE2MTUyMDk1OTAsImV4cCI6MTYxNTI5NTk5MH0.pz4c2VhCVrTc2Rb1NmWe_1BhBkqKwFxv4GRY0YU6D20

###
GET http://localhost:3600/api/crypto/list HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IjlmODZkMDgxODg0YzdkNjU5YTJmZWFhMGM1NWFkMDE1YTNiZjRmMWIyYjBiODIyY2QxNWQ2YzE1YjBmMDBhMDgiLCJpYXQiOjE2MTUyMDk1OTAsImV4cCI6MTYxNTI5NTk5MH0.pz4c2VhCVrTc2Rb1NmWe_1BhBkqKwFxv4GRY0YU6D20